### ISSUE TITLE
Ability to create, update, and delete books from the library

### ISSUE THREAD

**Issue by azotpdl0** [r-adelaide/cheltham#17]
For the MVP, the _librarian_ should be able to CREATE, UPDATE, and DELETE books from the library.

The appointed library _librarian_ should be able to make changes to the books that are stored in the library.

Acceptance criteria:
_Admin_ can create, update and delete books

**Comment by h-hollingsworth** [comment]
Admin can create, update, delete books using standard lightning experience using Book and Book Copy objects.
