### ISSUE TITLE
Add or remove book copies to the library

### ISSUE THREAD

**Issue by rody** [r-adelaide/cheltham#29]
As a library admin, I want to be able to add a copy to an existing book in the library. An admin should also be able to remove a copy without affecting the Book object.

Criterias:
 - A book copy must be linked to a book.
 - use standard platform UI

The required fields are:
-Book foreign key on Book Copy
-Status (set by default as Available on creation)
-Title (automatically added via Book)

Acceptance Criteria:
- [x] Admin can add a Book Copy to a Book
- [x] Admin can delete a Book Copy from a Book
- [x] Non-admin cannot add or delete a Book Copy
- [x] It should not be possible to create a Book Copy that does not have a Book: If an admin tries to make a Book Copy manually, validation cancels that action
- [x] If a Book is deleted, it's Book Copies are also removed

**Comment by azotpdl0** [comment]
Required field: Title
